config/routes.rb
Ppmm::Application.routes.draw do

	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	resources :datasets, only: [:new, :create, :show, :edit, :update]

	root to: 'static_pages#inicio'

	match '/ayuda', to: 'static_pages#ayuda'
	match '/empresa', to: 'static_pages#empresa'
	match '/contacto', to: 'static_pages#contacto'

	match '/registrarse', to: 'users#new'

	match '/iniciar_sesion', to: 'sessions#new'
	match '/cerrar_sesion', to: 'sessions#destroy', via: :delete

	match '/carga_de_datos', to: 'datasets#new'

end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
	attr_accessible :instance_size, :cavities, :batch_time, :products_composition, :install_time, :velocity, :demand, :machine_time
	belongs_to :user

	validates :user_id, presence: true
	validates :instance_size, presence: true
	validates :cavities, presence: true
	validates :batch_time, presence: true
	validates :products_composition, presence: true
	validates :install_time, presence: true
	validates :velocity, presence: true
	validates :demand, presence: true
	validates :machine_time, presence: true

	private

		def self.import(file,current_user)
			@user = current_user
			@dataset = @user.build_dataset
			@nil_flag = 0
			CSV.foreach(file.path, headers: false) do |row|
				if (row[0].blank? || row[1].blank? || row[2].blank? || row[3].blank? || row[4].blank? || row[5].blank? || row[6].blank? || row[7].blank?)
					@nil_flag = 0
				else
					@dataset.instance_size = row[0]
					@dataset.cavities = row[1]
					@dataset.batch_time = row[2]
					@dataset.products_composition = row[3]
					@dataset.install_time = row[4]
					@dataset.velocity = row[5]
					@dataset.demand = row[6]
					@dataset.machine_time = row[7]
					@dataset.save
					@nil_flag = 1
				end
				return @nil_flag
			end
		end
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :company, :email, :name, :telephone, :password, :password_confirmation
	has_secure_password
	has_one :dataset, dependent: :destroy

	before_save { |user| user.email = email.downcase }
	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :telephone, presence: true
	validates :company, presence: true
	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true

	private
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	include SessionsHelper

	# Force signout to prevent CSRF attacks
	def handle_unverified_request
		sign_out
		super
	end
end

app/controllers/datasets_controller.rb
#encoding: utf-8
class DatasetsController < ApplicationController

	def new
		@dataset = current_user.build_dataset
	end

	def create
		@result = Dataset.import(params[:file], current_user)
		if @result == 1
			flash[:success] = "Conjunto de datos creado."
			redirect_to dataset_path(current_user)
		else
			flash[:error] = "La información está incompleta. No es posible crear el conjunto de datos."
			redirect_to carga_de_datos_path
		end
	end

	def show
		@instance_size = current_user.dataset.instance_size.split(",").map(&:to_i)
		@cavities = current_user.dataset.cavities.split(",").map(&:to_i)
		@batch_time = current_user.dataset.batch_time.split(",").map(&:to_f)
		@products_composition = current_user.dataset.products_composition.split(",").map(&:to_i)
		@install_time = current_user.dataset.install_time.split(",").map(&:to_f)
		@velocity = current_user.dataset.velocity.split(",").map(&:to_f)
		@demand = current_user.dataset.demand.split(",").map(&:to_i)
		@machine_time = current_user.dataset.machine_time.split(",").map(&:to_f)
		gon.instance = @instance_size
		if current_user.admin?
			@user = User.find(params[:id])
			@dataset = @user.dataset
		else
			@user = current_user
			@dataset = @user.dataset
		end
	end

	def edit
		@user = current_user
		@dataset = @user.dataset
	end

	def update
		@user = current_user
		@dataset = @user.dataset
		if @dataset.update_attributes(params[:dataset])
			flash[:success] = "Conjunto de datos actualizado."
			redirect_to dataset_path(current_user)
		else
			flash[:error] = "La información está incompleta. No es posible actualizar el conjunto de datos."
			render 'edit'
		end
	end
end

app/controllers/sessions_controller.rb
#encoding: utf-8
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'El correo electrónico o la contraseña están incorrectos.'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def inicio
  end

  def ayuda
  end

  def empresa
  end

  def contacto
  end
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
	before_filter :signed_in_user, only: [:show, :index, :destroy, :edit, :update]
	before_filter :correct_user, only: [:show, :edit, :update]
	before_filter :admin_user, only: [:index, :destroy]

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			sign_in @user
			flash[:success] = "¡Bienvenido a la aplicación Logykopt-PPMM en línea!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			flash[:success] = "Perfil actualizado"
			sign_in @user
			redirect_to @user
		else
			render 'edit'
		end
	end

	def index
		@users = User.paginate(page: params[:page], per_page: 20)
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "Usuario eliminado."
		redirect_to users_url
	end

	private

		def signed_in_user
			unless signed_in?
				store_location
				redirect_to iniciar_sesion_url, notice: "Por favor, inicie sesión."
			end
		end

		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_path) && flash[:error] = "Acción inválida." unless (current_user?(@user) || current_user.admin?)
		end

		def admin_user
			redirect_to(root_path) && flash[:error] = "Acción inválida." unless current_user.admin?
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/helpers/sessions_helper.rb
#encoding: utf-8
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def current_user?(user)
		user == current_user
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url
	end

	def prior_dataset?
		!current_user.dataset.nil?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/datasets/edit.html.erb
<% provide(:title, "#{current_user.name} | Actualización de datos") %>
<h1>Actualizar datos</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user.dataset) do |f| %>
			<%= f.label :instance_size, "Tamaño de instancia" %>
			<%= f.text_field :instance_size %>

			<%= f.label :cavities, "Número de cavidades" %>
			<%= f.text_field :cavities %>

			<%= f.label :batch_time, "Tiempo de lote" %>
			<%= f.text_field :batch_time %>

			<%= f.label :products_composition, "Composición de productos" %>
			<%= f.text_field :products_composition %>

			<%= f.label :install_time, "Tiempo de instalación de moldes" %>
			<%= f.text_field :install_time %>

			<%= f.label :velocity, "Velocidad de procesamiento" %>
			<%= f.text_field :velocity %>

			<%= f.label :demand, "Demanda de productos" %>
			<%= f.text_field :demand %>

			<%= f.label :machine_time, "Tiempo máquina disponible" %>
			<%= f.text_field :machine_time %>

			<%= f.submit "Guardar cambios", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/datasets/new.html.erb
<% provide(:title, "#{current_user.name} | Carga de datos") %>
<h1>Cargar datos</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for @dataset, :html => { :multipart => true } do %>
			<%= hidden_field_tag 'current_user', @current_user %>
			<%= file_field_tag :file %>
			<%= submit_tag "Importar", style: 'margin-top: -10px', class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/datasets/show.html.erb
<% provide(:title, "#{current_user.name} | Conjunto de datos") %>

<div class="tabbable"> <!-- Required for left/right tabs -->
	<ul class="nav nav-tabs">
		<li class="active"><a href="#tab1" data-toggle="tab">Cavidades</a></li>
		<li><a href="#tab2" data-toggle="tab">Tiempo lote</a></li>
		<li><a href="#tab3" data-toggle="tab">Composición productos</a></li>
		<li><a href="#tab4" data-toggle="tab">Tiempo de instalación</a></li>
		<li><a href="#tab5" data-toggle="tab">Velocidad</a></li>
		<li><a href="#tab6" data-toggle="tab">Demanda</a></li>
		<li><a href="#tab7" data-toggle="tab">Tiempo máquina</a></li>
	</ul>
	<div class="tab-content">

		<div class="tab-pane active" id="tab1"> <!-- Active pane -->
			<hr style="border: 1px dashed #000;" />
			<h3>Número de cavidades.</h3>
			<% @instance_size[3].times.each do |m| %> <!-- For each machine -->
				<table id= <%= "cavities_" + m.to_s %> class="display" >
					<thead>
						<h4> <%= "Máquina " + (m + 1).to_s %> </h4>
						<tr align="center">
							<th> Molde/Pieza </th> <!-- Label -->
							<% @instance_size[1].times.each do |i| %> <!-- For each piece -->
								<th> <%= i + 1 %> </th> <!-- Label (piece) -->
							<% end %>
						</tr>
					</thead>

					<tbody>
						<% @instance_size[2].times.each do |j| %> <!-- For each mold -->
							<tr align="center">
							<th> <%= j + 1 %> </th> <!-- Label (mold) -->
							<% @instance_size[1].times.each do |i| %> <!-- For each piece -->
								<td> <%= @cavities[@instance_size[1] * @instance_size[2] * m + @instance_size[1] * j + i] %> </td> <!-- Prints each mold-piece pair -->
							<% end %>
							</tr>
						<% end %>
					</tbody>
				</table>
			<% end %>
			<hr style="border: 1px dashed #000;" />
		</div>

		<div class="tab-pane" id="tab2"> <!-- Pane change -->
			<hr style="border: 1px dashed #000;" />
			<h3>Tiempo de lote.</h3>
			<% @instance_size[3].times.each do |m| %> <!-- For each machine -->
				<table id= <%= "batch_time_" + m.to_s %> class="display">
					<thead>
						<h4> <%= "Máquina " + (m + 1).to_s %> </h4>
						<tr align="center">
							<th> Molde/Pieza </th> <!-- Label -->
							<% @instance_size[1].times.each do |i| %> <!-- For each piece -->
								<th> <%= i + 1 %> </th> <!-- Label (piece) -->
							<% end %>
						</tr>
					</thead>

					<tbody>
						<% @instance_size[2].times.each do |j| %> <!-- For each mold -->
							<tr align="center">
							<th> <%= j + 1 %> </th> <!-- Label (mold) -->
							<% @instance_size[1].times.each do |i| %> <!-- For each piece -->
								<td> <%= @batch_time[@instance_size[1] * @instance_size[2] * m + @instance_size[1] * j + i] %> </td> <!-- Prints each mold-piece pair -->
							<% end %>
							</tr>
						<% end %>
					</tbody>
				</table>
			<% end %>
			<hr style="border: 1px dashed #000;" />
		</div>

		<div class="tab-pane" id="tab3"> <!-- Pane change -->
			<hr style="border: 1px dashed #000;" />
			<h3>Composición de productos.</h3>
			<table id="products_composition" class="display">
				<thead>
					<tr align="center">
						<th> Producto/Pieza </th> <!-- Label -->
						<% @instance_size[1].times.each do |i| %> <!-- For each piece -->
							<th> <%= i + 1 %> </th> <!-- Label (piece) -->
						<% end %>
					</tr>
				</thead>

				<tbody>
					<% @instance_size[0].times.each do |p| %> <!-- For each product -->
						<tr align="center">
						<th> <%= p + 1 %> </th> <!-- Label (product) -->
						<% @instance_size[1].times.each do |i| %> <!-- For each piece -->
							<td> <%= @products_composition[i + p * @instance_size[1]] %> </td> <!-- Prints each product-piece pair -->
						<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
			<hr style="border: 1px dashed #000;" />
		</div>

		<div class="tab-pane" id="tab4"> <!-- Pane change -->
			<hr style="border: 1px dashed #000;" />
			<h3>Tiempo de instalación de moldes.</h3>
			<table id="install_time" class="display">
				<thead>
					<tr align="center">
						<th> Molde/Maquina </th> <!-- Label -->
						<% @instance_size[3].times.each do |k| %> <!-- For each machine -->
							<th> <%= k + 1 %> </th> <!-- Label (machine) -->
						<% end %>
					</tr>
				</thead>

				<tbody>
					<% @instance_size[2].times.each do |j| %> <!-- For each mold -->
						<tr align="center">
						<th> <%= j + 1 %> </th> <!-- Label (mold) -->
						<% @instance_size[3].times.each do |k| %> <!-- For each machine -->
							<td> <%= @install_time[k + j * @instance_size[3]] %> </td> <!-- Prints each mold-machine pair -->
						<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
			<hr style="border: 1px dashed #000;" />
		</div>

		<div class="tab-pane" id="tab5"> <!-- Pane change -->
			<hr style="border: 1px dashed #000;" />
			<h3>Velocidad de procesamiento.</h3>
			<table id="velocity" class="display">
				<thead>
					<tr align="center">
						<th> Producto </th> <!-- Label -->
						<% @instance_size[0].times.each do |p| %> <!-- For each product -->
							<th> <%= p + 1 %> </th> <!-- Label (product) -->
						<% end %>
					</tr>
				</thead>

				<tbody>
					<tr align="center">
						<th> Velocidad </th> <!-- Label (title) -->
						<% @instance_size[0].times.each do |p| %> <!-- For each product -->
							<td> <%= @velocity[p] %> </td> <!-- Prints each product -->
						<% end %>
					</tr>
				</tbody>
			</table>
			<hr style="border: 1px dashed #000;" />
		</div>

		<div class="tab-pane" id="tab6"> <!-- Pane change -->
			<hr style="border: 1px dashed #000;" />
			<h3>Demanda de productos.</h3>
			<table id="demand" class="display">
				<thead>
					<tr align="center">
						<th> Producto </th> <!-- Label -->
						<% @instance_size[0].times.each do |p| %> <!-- For each product -->
							<th> <%= p + 1 %> </th> <!-- Label (product) -->
						<% end %>
					</tr>
				</thead>

				<tbody>
					<tr align="center">
						<th> Demanda </th> <!-- Label (title) -->
						<% @instance_size[0].times.each do |p| %> <!-- For each product -->
							<td> <%= @demand[p] %> </td> <!-- Prints each product -->
						<% end %>
					</tr>
				</tbody>
			</table>
			<hr style="border: 1px dashed #000;" />
		</div>

		<div class="tab-pane" id="tab7"> <!-- Pane change -->
			<hr style="border: 1px dashed #000;" />
			<h3>Tiempo máquina disponible.</h3>
			<table id="machine_time" class="display">
				<thead>
					<tr align="center">
						<th> Máquina </th> <!-- Label -->
						<% @instance_size[3].times.each do |k| %> <!-- For each product -->
							<th> <%= k + 1 %> </th> <!-- Label (product) -->
						<% end %>
					</tr>
				</thead>

				<tbody>
					<tr align="center">
						<th> Tiempo máquina </th> <!-- Label (title) -->
						<% @instance_size[3].times.each do |k| %> <!-- For each product -->
							<td> <%= @machine_time[k] %> </td> <!-- Prints each product -->
						<% end %>
					</tr>
				</tbody>
			</table>
			<hr style="border: 1px dashed #000;" />
		</div>

	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Logykopt | Planeación Estratégica para Líneas de Manufactura con Máquinas de Inyección de Plástico.
	</small>
	<nav>
		<ul>
			<li><%= link_to "Acerca de nosotros", empresa_path %></li> <!-- Link to Empresa page. -->
			<li><%= link_to "Contacto", contacto_path %></li>	<!-- Link to Contacto page. -->
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">	<!-- Navigation bar configuration. -->
	<div class="navbar-inner">
	<div class="container">
		<%= link_to "Logykopt", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Inicio", root_path %></li>	<!-- Link to Inicio page. -->
					<li><%= link_to "Ayuda", ayuda_path %></li>	<!-- Link to Ayuda page. -->
					<% if signed_in? %>
						<% if current_user.admin? %>
							<li><%= link_to "Usuarios", users_path %></li>
						<% end %>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Datos <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<% unless prior_dataset? %>
									<li><%= link_to "Cargar nuevo conjunto de datos", carga_de_datos_path(current_user) %></li>
								<% end %>
								<% if prior_dataset? %>
									<li><%= link_to "Cargar nuevo conjunto", carga_de_datos_path(current_user),
										:confirm => "Esta acción reemplaza el conjunto de datos actual. ¿Desea continuar?" %></li>
									<li class="divider"></li>
									<li>
										<li><%= link_to "Mostrar conjunto de datos", dataset_path(current_user) %></li>
										<li><%= link_to "Modificar conjunto de datos", edit_dataset_path(current_user) %></li>
									</li>
								<% end %>
							</ul>
						</li>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Cuenta <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Perfil", current_user %></li>
								<li><%= link_to "Configuración", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li>
									<%= link_to "Cerrar sesión", cerrar_sesion_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% else %>
						<!-- <li><%= link_to "Iniciar sesión", iniciar_sesion_path %></li> -->
						<ul class="nav pull-right">
								<li class="divider-vertical"></li>
								<li class="dropdown">
								<a class="dropdown-toggle" href="#" data-toggle="dropdown">Iniciar sesión<strong class="caret"></strong></a>
								<div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
								<%= form_for(:session, url: sessions_path) do |f| %>
									<%= f.label :email, "Correo electrónico:" %>
									<%= f.text_field :email, :style => "width:200px" %>

									<%= f.label :password, "Contraseña:" %>
									<%= f.password_field :password, :style => "width:200px"  %>

									<div class="center">
										<%= f.submit "Iniciar sesión", class: "btn btn-primary" %>
									</div>
								<% end %>
								</div>
							</li>
						</ul>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Logykopt | Aplicación PPMM | <%= yield(:title) %></title> <!-- Title is common in all pages. -->
		<%= include_gon %>
		<%= stylesheet_link_tag "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>		
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/ayuda.html.erb
<% provide(:title, 'Ayuda') %>
<h1>Ayuda</h1>
<p>
	En esta sección se colocará un archivo de ayuda para el usuario.
</p>

app/views/static_pages/contacto.html.erb
<% provide(:title, 'Contacto') %>
<h1>Contáctanos</h1>
<p>
	Tels. oficina: 01800001122334455.<br/><br/>
	E-mail: <a href="mailto:m.a.saucedo.e@gmail.com">m.a.saucedo.e@gmail.com</a> 
</p>

app/views/static_pages/empresa.html.erb
<% provide(:title, 'Acerca de nosotros') %>
<h1>Nuestra Empresa</h1>
<p>
	Logykopt es una empresa tecnológica enfocada en la ciencia y la innovación.
</p>

app/views/static_pages/inicio.html.erb
<% provide(:title, 'Inicio') %>
<div class="center hero-unit">
	<h1>Aplicación PPMM</h1>
	<h2>
		Esta es la página inicial de nuestra aplicación en línea.
	</h2>
	<%= link_to "Registrarse", registrarse_path, class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("logykopt.png", :size=>'113x74', alt: "logykopt"), '/images/' %> <!-- Image must be inserted in app/assets/images. -->

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 52 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "Eliminar", user, method: :delete,
			data: { confirm: "¿Eliminar #{user.name}?" } %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "#{@user.name} | Edición del usuario") %>
<h1>Editar usuario</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label :name, "Nombre" %>
			<%= f.text_field :name %>

			<%= f.label :email, "Correo electrónico" %>
			<%= f.text_field :email %>

			<%= f.label :telephone, "Teléfono" %>
			<%= f.text_field :telephone %>

			<%= f.label :company, "Compañía" %>
			<%= f.text_field :company %>

			<%= f.label :password, "Contraseña" %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmar contraseña" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Guardar cambios", class: "btn btn-large btn-primary" %>
		<% end %>
		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails">Cambiar</a>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Lista de usuarios') %>
<h1>Lista de usuarios</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Registro') %>
<h1>Registrarse</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name, "Nombre" %>
			<%= f.text_field :name %>

			<%= f.label :email, "Correo electrónico" %>
			<%= f.text_field :email %>

			<%= f.label :telephone, "Teléfono" %>
			<%= f.text_field :telephone %>

			<%= f.label :company, "Compañía" %>
			<%= f.text_field :company %>

			<%= f.label :password, "Contraseña" %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmar contraseña" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Crear usuario", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name} | Perfil") %>
<div class="row">
	<aside class="span12">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
			<%= @user.company %>

			<h4>Datos del perfil.</h4>

				<h5 style="display:inline">Nombre: <h6 style="display:inline"><%= @user.name %>.</h6></h5><br><br>
				<h5 style="display:inline">Compañía: <h6 style="display:inline"><%= @user.company %>.</h6></h5><br><br>
				<h5 style="display:inline">Correo electrónico: <h6 style="display:inline"><%= @user.email %>.</h6></h5><br><br>
				<h5 style="display:inline">Teléfono: <h6 style="display:inline"><%= @user.telephone %>.</h6></h5>
		</section>
	</aside>
</div>